### ISSUE TITLE
We do not need `autoload-dev` section inside `composer.json`

### ISSUE THREAD

**Issue by creocoder** [2amigos/yii2-extension-skeleton#2]
Since `tests/bootstrap.php` contains alias `@tests` its also used for test files autoloading.

@tonydspaniard Can we remove that from `composer.json`?

**Comment by tonydspaniard** [comment]
Make sense

**Comment by tonydspaniard** [comment]
Seems that you already removed it :)

**Comment by vova07** [comment]
What about to leave this in `composer.json` and removed from `bootstrap` ? Seems more logical IMO.

**Comment by creocoder** [comment]
@vova07 Unfortunately normal unit testing with Yii 2 is impossible and it require application mock inside bootstrap. Since we have application instance and need Yii autoloading feature we can use Yii autoloader for tests.

**Comment by vova07** [comment]
Ok .... got it. Thank you @creocoder

**Comment by creocoder** [comment]
@vova07 Np, you are welcomed )
